USE restaurantDB;

INSERT INTO drink (name, type, price, alcoholic)
VALUES
('Agua', 'Refresco', 2.20, FALSE),
('Agua con gas', 'Refresco', 2.20, FALSE),
('Coca-Cola', 'Refresco', 2.50, FALSE),
('Coca-Cola Zero', 'Refresco', 2.50, FALSE),
('Coca-Cola S/C', 'Refresco', 2.50, FALSE),
('Pepsi', 'Refresco', 2.50, FALSE),
('Pepsi Max', 'Refresco', 2.50, FALSE),
('Sprite', 'Refresco', 2.50, FALSE),
('Fanta Naranja', 'Refresco', 2.50, FALSE),
('Fanta Limón', 'Refresco', 2.50, FALSE),
('Mirinda', 'Refresco', 2.50, FALSE),
('7UP', 'Refresco', 2.50, FALSE),
('Mountain Dew', 'Refresco', 2.50, FALSE),
('Dr Pepper', 'Refresco', 2.50, FALSE),
('Canada Dry', 'Refresco', 2.50, FALSE),
('Schweppes', 'Refresco', 2.50, FALSE),
('Lemonade', 'Refresco', 2.75, FALSE),
('Iced Tea', 'Refresco', 2.75, FALSE),
('Ginger Ale', 'Refresco', 2.50, FALSE),
('Tonic Water', 'Refresco', 2.50, FALSE),
('Lime Soda', 'Refresco', 2.50, FALSE),
('Orange Crush', 'Refresco', 2.50, FALSE),
('Grape Soda', 'Refresco', 2.50, FALSE),
('Cream Soda', 'Refresco', 2.50, FALSE),
('Root Beer', 'Refresco', 2.50, FALSE),
('Apple Cider', 'Refresco', 3.00, FALSE),
('Cabernet Sauvignon', 'Vino tinto', 25.00, TRUE),
('Merlot', 'Vino tinto', 20.00, TRUE),
('Syrah', 'Vino tinto', 30.00, TRUE),
('Pinot Noir', 'Vino tinto', 35.00, TRUE),
('Malbec', 'Vino tinto', 28.00, TRUE),
('Chardonnay', 'Vino blanco', 22.00, TRUE),
('Sauvignon Blanc', 'Vino blanco', 18.00, TRUE),
('Pinot Grigio', 'Vino blanco', 20.00, TRUE),
('Riesling', 'Vino blanco', 25.00, TRUE),
('Prosecco', 'Vino espumoso', 30.00, TRUE),
('Champagne', 'Vino espumoso', 50.00, TRUE),
('Cava', 'Vino espumoso', 25.00, TRUE),
('Moscato', 'Vino dulce', 18.00, TRUE),
('Port', 'Vino fortificado', 35.00, TRUE),
('Sherry', 'Vino fortificado', 30.00, TRUE),
('Marsala', 'Vino fortificado', 25.00, TRUE),
('Vermouth', 'Vino aromatizado', 20.00, TRUE),
('Rosé', 'Vino rosado', 22.00, TRUE),
('Zinfandel', 'Vino tinto', 28.00, TRUE),
('Gewürztraminer', 'Vino blanco', 25.00, TRUE),
('Margarita', 'Cóctel', 8.50, TRUE),
('Mojito', 'Cóctel', 9.00, TRUE),
('Daiquiri', 'Cóctel', 7.50, TRUE),
('Piña Colada', 'Cóctel', 8.00, TRUE),
('Cosmopolitan', 'Cóctel', 10.00, TRUE),
('Manhattan', 'Cóctel', 12.00, TRUE),
('Bloody Mary', 'Cóctel', 9.50, TRUE),
('Whiskey Sour', 'Cóctel', 8.00, TRUE),
('Gin Tonic', 'Cóctel', 7.50, TRUE),
('Mint Julep', 'Cóctel', 9.50, TRUE),
('Tequila Sunrise', 'Cóctel', 8.50, TRUE),
('Long Island Iced Tea', 'Cóctel', 12.50, TRUE),
('Rum and Coke', 'Cóctel', 6.50, TRUE),
('White Russian', 'Cóctel', 10.50, TRUE),
('Negroni', 'Cóctel', 11.00, TRUE);

INSERT INTO dishes (name, description, price, type, allergens)
VALUES 
('Ensalada César', 'Lechuga romana, pollo, crutones, queso parmesano, salsa César', 9.50, 'entrante', 'frutos secos'),
('Gazpacho', 'Sopa fría de tomate, pimiento, pepino, ajo y aceite de oliva', 6.50, 'entrante', 'apio, sulfitos'),
('Croquetas de jamón', 'Croquetas caseras de jamón serrano', 8.00, 'entrante', 'gluten, huevo, lácteos'),
('Tabulé', 'Ensalada libanesa de cuscús, tomate, pepino, cebolla, perejil, menta y limón', 7.50, 'entrante', 'frutos secos'),
('Hummus', 'Puré de garbanzos, tahini, aceite de oliva y limón', 6.00, 'entrante', 'sésamo'),
('Salmorejo', 'Sopa fría de tomate, pan, ajo, aceite de oliva y jamón serrano', 7.00, 'entrante', 'gluten, sulfitos'),
('Queso frito con mermelada de tomate', 'Queso manchego frito con mermelada casera de tomate', 9.00, 'entrante', 'lácteos'),
('Tortilla de patatas', 'Tortilla de patatas con cebolla', 8.00, 'entrante', 'huevo'),
('Carpaccio de calabacín', 'Calabacín laminado con queso parmesano, rúcula y aceite de oliva', 9.50, 'entrante', 'lácteos'),
('Boquerones en vinagre', 'Boquerones marinados en vinagre y aceite de oliva', 7.50, 'entrante', 'pescado'),
('Calamares a la romana', 'Calamares rebozados y fritos', 10.00, 'entrante', 'gluten, moluscos'),
('Pulpo a la gallega', 'Pulpo cocido con pimentón y aceite de oliva', 12.00, 'entrante', 'moluscos'),
('Ensaladilla rusa', 'Ensaladilla de patata, zanahoria, guisantes, atún, huevo y mayonesa', 6.50, 'entrante', 'huevo, pescado'),
('Gambas al ajillo', 'Gambas salteadas en aceite de oliva, ajo y guindilla', 11.00, 'entrante', 'marisco'),
('Tostada de salmón ahumado', 'Tostada de pan con salmón ahumado, queso crema y eneldo', 9.50, 'entrante', 'lácteos, pescado');

INSERT INTO dishes (name, description, price, type, allergens)
VALUES 
('Entrecot a la parrilla', 'Jugoso entrecot a la parrilla con patatas y verduras al grill', 22.50, 'carne', 'Gluten, lactosa'),
('Solomillo Wellington', 'Delicioso solomillo envuelto en hojaldre con patatas y salsa de champiñones', 28.75, 'carne', 'Gluten, huevo, frutos secos'),
('Rabo de toro estofado', 'Rabo de toro cocido a fuego lento con patatas y verduras', 18.95, 'carne', 'Apio'),
('Carrilleras en salsa', 'Carrilleras de cerdo en suave salsa con patatas fritas', 15.80, 'carne', 'Lactosa'),
('Chuletón de buey', 'Impresionante chuletón de buey a la brasa con patatas y pimientos', 32.90, 'carne', 'Lactosa'),
('Filete de ternera con foie', 'Filete de ternera con foie y reducción de vino tinto con patatas fritas', 24.50, 'carne', 'Lactosa'),
('Cordero asado', 'Cordero asado con patatas y cebolla caramelizada', 19.75, 'carne', 'Lactosa'),
('Costillas BBQ', 'Costillas de cerdo a la BBQ con patatas fritas y ensalada', 16.20, 'carne', 'Lactosa, sulfitos'),
('Bistec a la plancha', 'Bistec de ternera a la plancha con patatas y ensalada', 14.95, 'carne', 'Lactosa'),
('Magret de pato', 'Magret de pato con salsa de frutos rojos y patatas duquesa', 21.50, 'carne', 'Lactosa'),
('Carpaccio de buey', 'Finas lonchas de buey con rúcula y parmesano', 12.75, 'carne', 'Lactosa'),
('Hamburguesa de la casa', 'Hamburguesa de ternera casera con patatas y ensalada', 13.50, 'carne', 'Gluten, lactosa'),
('Lomo de cerdo al horno', 'Lomo de cerdo asado con patatas y ensalada', 15.25, 'carne', 'Lactosa'),
('Pollo al curry', 'Pollo en salsa de curry con arroz basmati', 13.95, 'carne', 'Lactosa'),
('Escalope de ternera', 'Escalope de ternera con patatas fritas y ensalada', 14.50, 'carne', 'Gluten, lactosa');

INSERT INTO dishes (name, description, price, type, allergens) VALUES
("Salmón a la parrilla", "Salmón a la parrilla con limón y hierbas", 15.99, "pescado", "sin alérgenos"),
("Atún con salsa de soja", "Atún fresco con salsa de soja y jengibre", 18.99, "pescado", "contiene soja"),
("Paella de mariscos", "Arroz con mariscos y verduras", 22.50, "pescado", "sin alérgenos"),
("Ceviche de pescado", "Pescado marinado en limón y especias, con cebolla y cilantro", 12.99, "Pescado", "sin alérgenos"),
("Lubina al horno", "Lubina al horno con patatas y tomate", 17.99, "pescado", "sin alérgenos"),
("Calamares a la romana", "Calamares rebozados y fritos", 10.50, "pescado", "contiene gluten"),
("Bacalao a la vizcaína", "Bacalao con salsa de tomate y pimientos", 19.99, "pescado", "sin alérgenos"),
("Sardinas a la parrilla", "Sardinas a la parrilla con aceite y limón", 13.50, "pescado", "sin alérgenos"),
("Ensalada de salmón", "Ensalada de lechuga con salmón ahumado, aguacate y vinagreta de mostaza", 14.99, "pescado", "sin alérgenos"),
("Trucha a la plancha", "Trucha a la plancha con ajo y perejil", 16.50, "pescado", "sin alérgenos"),
("Sopa de pescado", "Sopa de pescado con trozos de pescado, verduras y fideos", 8.99, "pescado", "sin alérgenos"),
("Boquerones en vinagre", "Boquerones marinados en vinagre y aceite de oliva", 7.50, "pescado", "sin alérgenos"),
("Tacos de pescado", "Tacos de pescado con salsa de aguacate y cilantro", 11.99, "pescado", "contiene lácteos"),
("Rodaballo al horno", "Rodaballo al horno con patatas y cebolla", 21.99, "pescado", "sin alérgenos"),
("Brocheta de langostinos", "Brocheta de langostinos a la parrilla con verduras", 19.50, "pescado", "sin alérgenos"),
("Gazpacho de melón con langostinos", "Gazpacho de melón con langostinos y jamón serrano", 12.99, "pescado", "contiene lácteos");

INSERT INTO dishes (name, description, price, type, allergens)
VALUES
("Margarita", "Salsa de tomate, mozzarella y albahaca", 9.99, "pizza", "Gluten"),
("Hawaiana", "Salsa de tomate, mozzarella, jamón y piña", 11.99, "pizza", "Gluten, lactosa"),
("Pepperoni", "Salsa de tomate, mozzarella y pepperoni", 10.99, "pizza", "Gluten, lactosa"),
("Cuatro quesos", "Salsa de tomate, mozzarella, gorgonzola, parmesano y provolone", 12.99, "pizza", "Gluten, lactosa"),
("Mexicana", "Salsa de tomate, mozzarella, carne de ternera picada, jalapeños y guacamole", 13.99, "pizza", "Gluten, lactosa"),
("Barbacoa", "Salsa barbacoa, mozzarella, pollo, bacon y cebolla", 12.99, "pizza", "Gluten, lactosa"),
("Mediterránea", "Salsa de tomate, mozzarella, aceitunas, cebolla, atún y tomate", 11.99, "pizza", "Gluten, lactosa, pescado"),
("Vegetariana", "Salsa de tomate, mozzarella, champiñones, pimiento, cebolla y aceitunas", 10.99, "pizza", "Gluten, lactosa"),
("Calzone", "Salsa de tomate, mozzarella, jamón, champiñones, cebolla y huevo", 11.99, "pizza", "Gluten, lactosa, huevo"),
("Carbonara", "Salsa de nata, mozzarella, bacon y huevo", 12.99, "pizza", "Gluten, lactosa, huevo"),
("Marinera", "Salsa de tomate, mozzarella, marisco y ajo", 13.99, "pizza", "Gluten, lactosa, marisco"),
("Prosciutto e funghi", "Salsa de tomate, mozzarella, jamón y champiñones", 11.99, "pizza", "Gluten, lactosa"),
("Tres carnes", "Salsa de tomate, mozzarella, carne de ternera picada, pepperoni y bacon", 13.99, "pizza", "Gluten, lactosa"),
("Caprese", "Salsa de tomate, mozzarella, tomate y albahaca", 10.99, "pizza", "Gluten, lactosa"),
("Serrana", "Salsa de tomate, mozzarella, chorizo, pimiento y cebolla", 11.99, "pizza", "Gluten, lactosa");

INSERT INTO dessert (name, description, price, allergens)
VALUES 
('Tarta de manzana', 'Deliciosa tarta de manzana casera', 3.50, 'Huevo, gluten'),
('Brownie', 'Tierno brownie de chocolate', 4.20, 'Frutos secos, soja'),
('Flan de vainilla', 'Suave y cremoso flan de vainilla', 2.75, 'Lactosa'),
('Tiramisú', 'Postre italiano de bizcochos y mascarpone', 5.00, 'Huevo, lactosa'),
('Cheesecake', 'Pastel de queso con galleta y frutos rojos', 4.50, 'Gluten, lactosa'),
('Mousse de chocolate', 'Espuma de chocolate negro y nata montada', 3.80, 'Huevo, lactosa'),
('Helado de vainilla', 'Clásico helado cremoso de vainilla', 2.00, 'Lactosa'),
('Helado de chocolate', 'Helado de fresa hecho con frutas frescas', 2.00, 'Lactosa'),
('Helado de nata', 'Helado de fresa hecho con frutas frescas', 2.00, 'Lactosa'),
('Helado de fresa', 'Helado de fresa hecho con frutas frescas', 2.00, 'Lactosa'),
('Crema catalana', 'Postre típico catalán con caramelo quemado', 3.50, 'Huevo, lactosa'),
('Coulant de chocolate', 'Bomba de chocolate con corazón líquido', 4.75, 'Huevo, gluten'),
('Pastel de zanahoria', 'Bizcocho de zanahoria con frosting de queso', 4.25, 'Gluten, lactosa'),
('Profiteroles', 'Bolitas de masa rellenas de nata y cubiertas de chocolate', 3.95, 'Huevo, gluten, lactosa'),
('Tarta de queso', 'Tarta de queso con mermelada de frutos rojos', 4.50, 'Huevo, gluten, lactosa'),
('Cupcake de vainilla', 'Magdalena con crema de vainilla y topping de chocolate', 2.75, 'Huevo, gluten, lactosa'),
('Macedonia de frutas', 'Selección de frutas frescas cortadas en trozos', 3.00, 'Ninguno'),
('Gelatina de limón', 'Gelatina de limón con trozos de frutas', 2.50, 'Ninguno'),
('Arroz con leche', 'Postre tradicional de arroz con leche y canela', 3.25, 'Lactosa'),
('Natillas', 'Postre casero de leche, huevos y azúcar', 2.95, 'Huevo, lactosa'),
('Tarta de chocolate', 'Tarta de chocolate negro con base de galleta', 4.50, 'Gluten, lactosa'),
('Crepe de nutella', 'Crepe de harina de trigo rellena de nutella', 3.75, 'Gluten, lactosa');
